version: '3.7'
services:

  swagger:
    image: swaggerapi/swagger-ui:latest
    volumes:
    - type: bind
      source: ./misc
      target: /foo
    ports:
    - "8080:8080"
    environment:
      SWAGGER_JSON: /foo/RestToDicom.yaml

  resttodicom:
    build:
      context: .
    image: resttodicom:latest
    #command: --key /irislicense/iris.key
    command: --check-caps false
    hostname: resttodicom
    ports:
    - "50776:51773" # 51773 is the superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
      - ./:/irisdev/app

